#!/usr/bin/env node
// Generated by CoffeeScript 1.9.1
(function() {
  var coffeeJoin, main, optimist, write;

  optimist = require('optimist');

  coffeeJoin = require("./coffee-join");

  write = require("./utils").write;

  main = function() {
    var argv, input_files, usage;
    usage = 'Usage: $0 input_file';
    argv = optimist.usage(usage).demand([1, 'o']).alias('o', 'output').describe('o', 'Output File path.').argv;
    input_files = argv._;
    return coffeeJoin.process_files(input_files, argv['o']);
  };

  if (require.main === module) {
    main();
  }

}).call(this);
