// Generated by CoffeeScript 1.9.1
(function() {
  var SourceMapConsumer, SourceMapGenerator, basename, coffeeScript, colors, compile, concat_files, dirname, print, process, re_order_source_map, read, ref, ref1, relative, write;

  coffeeScript = require("coffee-script");

  ref = require("./utils"), print = ref.print, relative = ref.relative, dirname = ref.dirname, read = ref.read, write = ref.write, basename = ref.basename;

  ref1 = require('source-map'), SourceMapConsumer = ref1.SourceMapConsumer, SourceMapGenerator = ref1.SourceMapGenerator;

  colors = require("colors");

  compile = function(code, name, bare) {
    var ret;
    if (name == null) {
      name = "file.coffee";
    }
    if (bare == null) {
      bare = true;
    }
    ret = coffeeScript.compile(code, {
      bare: bare,
      sourceMap: true,
      filename: name
    });
    return {
      code: ret.js,
      map: JSON.parse(ret.v3SourceMap)
    };
  };

  re_order_source_map = function(line_number_mapping, map, out_js_file, out_map_file, code) {
    var generator, rel_js_file, rel_map_file, sourceMap;
    rel_map_file = relative(dirname(out_js_file), out_map_file);
    rel_js_file = relative(dirname(out_map_file), out_js_file);
    code += "\n//@ sourceMappingURL=" + rel_map_file;
    generator = new SourceMapGenerator({
      file: rel_js_file
    });
    map = new SourceMapConsumer(map);
    map.eachMapping(function(mapping) {
      var line, path;
      line = line_number_mapping[mapping.originalLine - 1];
      path = relative(dirname(out_js_file), line.path);
      mapping = {
        generated: {
          line: mapping.generatedLine,
          column: mapping.generatedColumn
        },
        original: {
          line: line.line_number,
          column: mapping.originalColumn
        },
        source: path
      };
      return generator.addMapping(mapping);
    });
    sourceMap = generator.toString();
    return {
      sourceMap: sourceMap,
      code: code
    };
  };

  concat_files = function(files) {
    var code, ex, file, file_name, i, j, len, len1, line, line_number, line_number_mapping, lines, map, ref2, source, sourceLines;
    sourceLines = [];
    line_number_mapping = [];
    for (i = 0, len = files.length; i < len; i++) {
      file = files[i];
      source = read(file);
      lines = source.split("\n");
      file_name = file;
      line_number = 1;
      for (j = 0, len1 = lines.length; j < len1; j++) {
        line = lines[j];
        sourceLines.push(line);
        line_number_mapping.push({
          path: file_name,
          line_number: line_number
        });
        line_number += 1;
      }
    }
    source = sourceLines.join("\n");
    try {
      ref2 = compile(source, "main.coffee", false), code = ref2.code, map = ref2.map;
    } catch (_error) {
      ex = _error;
      print("Error occured while compiling coffeescript.".red);
      print(source);
      process.exit(1);
    }
    return {
      code: code,
      map: map,
      line_number_mapping: line_number_mapping
    };
  };

  process = function(files, output) {
    var code, line_number_mapping, map, out_js_file, out_map_file, ref2, ref3, sourceMap;
    output = basename(output, ".js");
    out_js_file = output + ".js";
    out_map_file = output + ".map";
    ref2 = concat_files(files), code = ref2.code, map = ref2.map, line_number_mapping = ref2.line_number_mapping;
    ref3 = re_order_source_map(line_number_mapping, map, out_js_file, out_map_file, code), sourceMap = ref3.sourceMap, code = ref3.code;
    write(out_js_file, code);
    return write(out_map_file, sourceMap);
  };

  module.exports = {
    compile: compile,
    concat_files: concat_files,
    re_order_source_map: re_order_source_map,
    process: process
  };

}).call(this);
